### ISSUE TITLE
git commit

### ISSUE THREAD

**Issue by defeo** [in202-uvsq/git-manual#1]
Décrire la commande `git commit`. Décrire en particulier les options

- `git commit -m`
- `git commit -a`
- `git commit --amend`

Assigné à : @Ylen96, @Gruudu, @KaneBoubacar .

**Comment by Ylen96** [comment]
je viens de mettre un premier jet du commit -m pensez a récupérer le fichier a jour avant de renvoyer une mise a jour :D

**Comment by Gruudu** [comment]
J'ai fini la description du commit --amend mais je ne sais pas comment vous l'envoyer pour que l'on fusionne ce que l'on à fait ^^"

**Comment by Ylen96** [comment]
avec la commande pull --ff-only tu devrais pvr recuperer ce qui a etait mis a jour tu aura juste à y incorporez ta description et a renvoyer sur git comme d'habitude

**Comment by KaneBoubacar** [comment]
Yo, j'ai fait un pull request a Ylen, je comprends pas pourquoi je n'y arrive pas avec Charlotte, voici quand même l'intitulé : 
[  J'ai fais le début des parties "-a" et "--amend"
Mais je n'ai pas remplis les parties que git affiche dans la console, tout simplement parce que je suis pas sûr... 
Si vous acceptez ce pull request vous aurez la page "Git_commit.html" dans le dossier "commandes" (les modifications ne seront appliquées que sur le répertoire git. Il faudra donc faire un "git pull" pour recupérer les changements sur vos ordis. La vous pourrez modifier les fichiers.
Une fois terminer il faudra "add" puis commiter avant de push dans votre répertoire.
Je ne sais pas qui sera la dernière personne à faire les modifications mais elle devra effectuer un pull request vers le repertoir "in-202/gh-pages". J'ai cru comprendre qu'il fallait le faire avant lundi pour permettre à une autre personne d'effectuer son travail.

Si vous le saviez déjà, dsl...

Bonne journée.  ]

Du coup, si Ylen tu arrives à faire un pull request vers Charlotte, bah c'est cool, sinon Charlotte, tu peux toujours utiliser la commande "git remote add ..." comme expliqué dans le wiki du répertoire in-202, et ainsi pull les modifications effectuer depuis mon répertoire git (ou celui de Ylen).

Je vais essayer de rester dispo en début d'aprèm si je peux aider.
Peace.

**Comment by Ylen96** [comment]
hello j'ai bien recuperer la pull request de KaneBoubacar, j'ai donc aussi repris le HTML pr ajuster le code du squelette avec les balises "code" donc la structure est impec. Je vais tenter la pull request a gruudu mais je pense que on peut envoyer une pull request aux admin vu que la structure correpond à la leur

**Comment by Ylen96** [comment]
alors j'ai bien essayer de faire la pull request mais n'ayant aucune reponse je soupconne  des conflits deplus je ne sais pas si j'aurais la main pour vu que dans le wiki il presente la personne qui cree la pages comme celui-qui doit faire la pull request ... voilou

**Comment by Ylen96** [comment]
salut, alors j'ai le fichier git-commit pratiquement complet @Gruudu j'ai récupérer ta partie, je viens de faire une actualisation du squelette ce soir je pense faire une pull request finale si vous voulez jetez un œil tout est sur ma gh-pages. bonne journee

**Comment by Misscouettes** [comment]
Tout est bon ici ?

**Comment by Ylen96** [comment]
c'est fini ici 
@in202-uvsq/2014-2015
