### ISSUE TITLE
git remote, git fetch

### ISSUE THREAD

**Issue by defeo** [in202-uvsq/git-manual#10]
Décrire les commandes `git remote` et `git fetch`. Décrire en particulier les sous-commandes

- `git remote add`,
- `git remote rename`,
- `git remote remove`,
- `git remote set-url`,

Détailler les options

- `git remote -v`,
- `git fetch --all`,
- `git fetch --dry-run`,
- `git fetch -t`.

Assigné à: @LowD , @Ousam , @yobero

**Comment by yobero** [comment]
Je m'occupe de git remote, git remote add, rename.

**Comment by LowD** [comment]
Ok, je m'occupe de git fetch, git fetch --all, et git fetch --dry-run.

**Comment by Ousam** [comment]
Je prends git remove, git remote set-url et git-fetch -v

**Comment by yobero** [comment]
j'ai créé la page pour mettre les commandes git remote ...

**Comment by yobero** [comment]
Je vais faire l'intermédiaire entre nos pages et le site commun
Pour forrt notre partie c'est ici : 
https://github.com/yobero/git-manual

Les deux pages sont prête à être remplie

**Comment by yobero** [comment]
Premier pull request envoyé et en attente de validation

**Comment by Nambrok** [comment]
@defeo Il est vrai que l'option `-r` n'existe pas pour la commande fetch.

**Comment by yobero** [comment]
La commande git fetch -r est en suspend, vous pouvez fork à l'addresse : https://github.com/yobero/git-manual

PS : ne modifier pas le fichier git-revert.html

**Comment by defeo** [comment]
Mon typo, je voulais dire `fetch -t`.

**Comment by yobero** [comment]
ok merci

**Comment by Ousam** [comment]
Je t'envoi tout ca ce soir yobero d'ici peu de temps

**Comment by yobero** [comment]
ok je ferai le pull request demain matin

**Comment by Ousam** [comment]
Pas de problème j'ai déjà fait git remote remove je te fais une pull request

**Comment by yobero** [comment]
dac

**Comment by Ousam** [comment]
j ai un probleme pour forker le tien justement

**Comment by Ousam** [comment]
comment as tu fais pour les autres ?

**Comment by yobero** [comment]
tu es en train de faire un pull request sur in202-uvsq... et pas sur yobero...

**Comment by Ousam** [comment]
oui je sais mais comment est ce que tu fais

**Comment by yobero** [comment]
faut déjà que tu supprime ton rep git-manual mais avant tu vas copier ta commande git remote remove dans un fichier séparer.

**Comment by Ousam** [comment]
okok

**Comment by Ousam** [comment]
mais je crois que c'est bon nan ? vérifie

**Comment by Ousam** [comment]
tu as merge c'est bon ?

**Comment by yobero** [comment]
oui mais met tes commandes dans la page git-remote directement dans le dossier commandes

Je vais mettre git remote remove dans la page directement

**Comment by Ousam** [comment]
je l'ai déjà mis sauf si je l'ai mal fais

**Comment by yobero** [comment]
A la limite c pas grave je les mettrai manuellement dans la page après ton pull request

**Comment by Ousam** [comment]
d'accord pas de problème

**Comment by Ousam** [comment]
je t'envoye les autres fonctions

**Comment by Ousam** [comment]
je le ferai de la même facon

**Comment by yobero** [comment]
ok

**Comment by yobero** [comment]
@Ousam 
Je viens de remarqué tu a créé un page git-remote-remove.html et tu dois l'écrire dans git-remote.html

Faut pas séparer les commandes git remote ...

**Comment by Ousam** [comment]
ok je corrige tout sa

**Comment by yobero** [comment]
sauf git remote remove c déjà fait.

**Comment by Ousam** [comment]
okok

**Comment by Ousam** [comment]
il me reste git fetch -v et on doit etre ok

**Comment by yobero** [comment]
ok

**Comment by Ousam** [comment]
tu as deja fait git -v @yobero ??

**Comment by yobero** [comment]
git fetch -v ?

**Comment by Ousam** [comment]
oui ?

**Comment by yobero** [comment]
non c Lowd
Pourquoi ?

**Comment by Ousam** [comment]
okok
parce que j'étais entrain de la faire mais je crois qu'on a tout fait

**Comment by yobero** [comment]
toi oui moi aussi mais pas Lowd
il manque git fetch --all
git fetch --dry-run
et je crois que c tout

**Comment by Ousam** [comment]
okok c'est bon alors

**Comment by yobero** [comment]
oui

**Comment by Ousam** [comment]
Très bien pas de soucis !

**Comment by yobero** [comment]
@LowD je m'occupe de ton pull request en rentrant.
Pas contre t a pas mis d'exemple.

**Comment by yobero** [comment]
@LowD @Ousam Les pages sont terminées, il manque juste l'exemple de git fetch --al et --dry-run.

Le pull request est envoyé.

**Comment by LowD** [comment]
Je ne trouve pas d'exemple pour --dry-run, j'envoie mon dernier pull request dans moins de 10 minutes.

**Comment by Misscouettes** [comment]
Yop, c'est bon vous avez fini ici ?

**Comment by LowD** [comment]
J'ai envoyé mon dernier pull request à @yobero.

**Comment by yobero** [comment]
Pas eu le temps désoler 
Le problème c'est que tu fait des pull request avec git rebase dont je ne dois pas modifier.

**Comment by LowD** [comment]
Y'a pas moyen que tu acceptes git rebase ? C'est pas grave si tu l'envoie avec ?

**Comment by yobero** [comment]
si je n'ai pas le droit d'envoyer une page dont je ne suis pas affecté

**Comment by LowD** [comment]
Ah, mais je sais pas comment faire pour enlever le rebase

**Comment by yobero** [comment]
tkt j'ai fais ce qui faut pour le mettre sans prendre l'autre
je viens d'envoye le pull mais je ne pense pas que sa passera
