### ISSUE TITLE
Bilan

### ISSUE THREAD

**Issue by Misscouettes** [in202-uvsq/git-manual#106]
Alors, j'ai noté les trucs qui allaient pas sur le site : 
-git branch : manque des lignes de syntaxe 
-git diff : manque des descriptions et un syntaxe
-git rebase : il y a un "..." dans la console. Je pense que c'est pour dire qu'ils n'ont pas d'exemples
-git fetch : manque le nom des participants
-git status : dans -b, il y a un problème au niveau de l'affichage de la console (ils ont du écrire en dehors des balises) + pas l'image en haut
-git checkout : énorme problème au niveau de l'affichage (trop d'espaces, ils ont écrit en dehors des balises etc)
-git clone : il n'y a que le git clone --bare et il n'y a pas d'exemples
-git init : idem
-git push : pas d'exemples pour les commandes (mais la personne qui l'a fait ne pouvait pas faire les exemples la console ne marchait pas chez lui)
-git reset : trop de blancs et manques des descriptifs

Sinon pour le reste dans l'ensemble ça va, on a un bon affichage (wp Corentin) et tout le reste est bien décrit.

**Comment by Misscouettes** [comment]
Etant donné que j'ai mis du temps à écrire ce truc et à tout vérifier, il y a eu peut-être des mises à jours entre-temps

**Comment by Nambrok** [comment]
Non, nous n'acceptons plus les pull requests, version définitive.

**Comment by Misscouettes** [comment]
@ducks-skills veut arranger l'affichage de certaines pages qui ont de gros problèmes (genre git checkout). Il peut ?

**Comment by Emaltard** [comment]
On modifie checkout pour mieux integrer le css. Ce sera la dernière modification je pense.

**Comment by Emaltard** [comment]
Checkout Done.
Des dernières volontés?

**Comment by ducks-skills** [comment]
oui me laisser faire les reglages parceque ...

**Comment by ducks-skills** [comment]
C'est DU GROS

**Comment by Emaltard** [comment]
Les réglages?

**Comment by ducks-skills** [comment]
N I M P O R T E Q U O I

**Comment by ducks-skills** [comment]
Les gens ont fait que de la merde

**Comment by ducks-skills** [comment]
bah y a pas une page qui saffiche bien quoi : git fecth // probleme de footer
git remote// probleme (mineur) de balise code
git revert// probleme de titre
git status// affichage en dehors de la console, image du logo non chargée
git checkout // limite page a supprimer, css a refaire a 30%
git clone// gros branleur qui a fait la page, et en plus il se permet de modifier le titre
git init// mauvais encodage, 
git log // titre mauvais de la page
git merge// ajouter le logo et corriger des erreurs mineures
git mv// meme genre de probleme
git pull// ajouter logo
git push// changer titre, ajouter des trucs dans la console
git reset// modifications complete de la page a faire 
git rm// ajouter un logo
git show// changer le titre
git tags// légères modifs a faire
identification des commits// legeres modifs a faire 
derniere page // titre a refaire

**Comment by Nambrok** [comment]
J'ai refait (un peu) git_checkout.html.
On n'a pas vraiment le temps de refaire le tout ce soir. Avec @Emaltard , on a corrigé les pages qui avait le CSS qui s'affichait bizzarement (ou pas du tout). Le contenu n'est pas vraiment notre problème à l'origine non plus.

**Comment by ducks-skills** [comment]
non mais la balise h1 NE devait PAS être modifiée

**Comment by Nambrok** [comment]
ça me gène pas plus que ça.

**Comment by ducks-skills** [comment]
Oui mais je m'en bas les couilles c'est moi qui ai fait le design on le respecte .

**Comment by Emaltard** [comment]
Pour un titre dans le navigateur? Tu es serieux? Modifier toutes les pages?

**Comment by ducks-skills** [comment]
non celles qui ne rescpectent pas le css

**Comment by ducks-skills** [comment]
soit 1/4

**Comment by Misscouettes** [comment]
Le contenu on change pas, mais si Corentin veut réparer l'affichage de certains, il peut quand même. C'est lui qui a fait le CSS quoi

**Comment by ducks-skills** [comment]
Voila +1

**Comment by Nambrok** [comment]
Bref, je vais me coucher, les pages sont biens comme elles sont, l'affichage est correct. **Bonne nuit**

**Comment by ducks-skills** [comment]
Bonne nuit et merci pour ton soutien heureusement que je peux compter sur les autres Releases masters !

**Comment by Emaltard** [comment]
Ah mais tu veux remettre le logo et le href. Ok. Tu fais tout ou je t'aide?

**Comment by ducks-skills** [comment]
Je met Le fantastique guide de Git sur tout les h1, le logo et le href aussi

**Comment by ducks-skills** [comment]
et le titre de la commande en h3 juste en bas du body

**Comment by Emaltard** [comment]
Désolé pour Nambrok il est juste crevé. On a fait des modifications toutes la soirée.

**Comment by Misscouettes** [comment]
On avait remarqué ^^

**Comment by ducks-skills** [comment]
Oui j'ai fait 4h de sport je me suis levé a 7h et ca fait 3jours que j'ai moins de 5H de sommeil et ca m'empeche pas de bosser enfin ...

**Comment by Emaltard** [comment]
Le fait que tu as été legerement agressif aussi n'a pas aidé, il faut comprendre les deux partis.

**Comment by Emaltard** [comment]
Bref, finissons ceci et reposons nous. Tu ne veux pas que je m'occupe de certaines pages?

**Comment by Misscouettes** [comment]
futur médiateur

**Comment by Misscouettes** [comment]
si vous avez besoin d'aide, je suis là aussi

**Comment by ducks-skills** [comment]
Oui mais voilà j'avais juste envie que l'on m'écoute bref affaire classée; oui euh de toutes celles ou il y a le titre a changer le reste je le fait

**Comment by Emaltard** [comment]
OK.

**Comment by Emaltard** [comment]
Je laisse quand meme le nom de la commande dans h1?

**Comment by ducks-skills** [comment]
Euh non tu le met dans la div corps avec un h3 stp

**Comment by Emaltard** [comment]
Donc: "Le fanstatique blablal" dans le h1 a chaque fois.

**Comment by ducks-skills** [comment]
voila plus le logo

**Comment by Emaltard** [comment]
J'ai fait toutes les modfis. J'envoie sur direct sur le site ou on fait autrement?

**Comment by ducks-skills** [comment]
euh ouais

**Comment by ducks-skills** [comment]
comme ca je verrais deux ou trois trucs merci BCP

**Comment by Emaltard** [comment]
Tu va devoir recuperer ces modifications et refaire les tiennes derriere donc.

**Comment by ducks-skills** [comment]
ouais tkt pas

**Comment by Emaltard** [comment]
Voila. Dis moi si j'ai fait des conneries.

**Comment by ducks-skills** [comment]
Okey

**Comment by ducks-skills** [comment]
c'est bon :)

**Comment by Emaltard** [comment]
Besoin d'aide encore?

**Comment by ducks-skills** [comment]
euh nan misscouettes va m'aider, donc euh bah tu peux aller te reposer

**Comment by Emaltard** [comment]
Je ne suis pas fatigué moi :) Hesitez pas en tout cas ! Je reste sur la page avec mon deuxieem ecran.

**Comment by ducks-skills** [comment]
okey

**Comment by Misscouettes** [comment]
comment tu te la pètes avec ton deuxieme écran

**Comment by Emaltard** [comment]
Jalouse :)

**Comment by Misscouettes** [comment]
jpréfère alt+tab que faire un voyage de 3 kilomètres avec ma souris

**Comment by Emaltard** [comment]
Je prefere avori une page en vision périphérique tout en travaillant sur une autre.

**Comment by Misscouettes** [comment]
J'ai test, et à part pour regarder des streams en attendant un truc sur un autre jeu, je vois pas trop l'utilité

**Comment by ducks-skills** [comment]
Je prefere les deux

**Comment by Emaltard** [comment]
Oh. Je regarde des streams 90% du temps :D Et puis pour du photoshop/3D/programmation c'est très sympa :D

**Comment by ducks-skills** [comment]
Regarder des streams est illégal voyons !

**Comment by Misscouettes** [comment]
Des streams sur twitch boloss

**Comment by Misscouettes** [comment]
Pas des séries en streaming

**Comment by ducks-skills** [comment]
Oui mais je me doute que y a d'autres streams

**Comment by Misscouettes** [comment]
Des trucs de JEUX VIDEOS

**Comment by Misscouettes** [comment]
DES VRAIS. Pas fifa

**Comment by ducks-skills** [comment]
Seul FIFA est un jeux vidéo

**Comment by Emaltard** [comment]
Ahaha.

**Comment by Misscouettes** [comment]
First !

**Comment by Emaltard** [comment]
Merci d'embellir ma soirée.

**Comment by Misscouettes** [comment]
tkt on est là pour ça

**Comment by ducks-skills** [comment]
Ouais #sisilafamille

**Comment by Misscouettes** [comment]
corentin c'est la mascotte

**Comment by Emaltard** [comment]
Mouais. On va pas être pote si tu continu tes #

**Comment by Misscouettes** [comment]
+1

**Comment by ducks-skills** [comment]
Qui a dit qu'on etais amis on ne se connait pratiquement pas mdr

**Comment by Misscouettes** [comment]
HAN POPOPOOOOO

**Comment by Misscouettes** [comment]
Bon les enfants on se calme

**Comment by Emaltard** [comment]
pote=/=ami

**Comment by Ylen96** [comment]
merci de nous faire partager à tous vos ressentis en tant que release manager :D exelente fin de soirée bien cordialement .

**Comment by Emaltard** [comment]
Filez moi vos skype et je ferme cette issue.

**Comment by Misscouettes** [comment]
Bah quoi c'est marant

**Comment by Misscouettes** [comment]
Puis le prof va lire

**Comment by Misscouettes** [comment]
Il va rigoler aussi

**Comment by Misscouettes** [comment]
bon sinon c'est erminera mon skype

**Comment by ducks-skills** [comment]
Et il va nous mettre zero il sera desespéré

**Comment by Melanie13340** [comment]
Moi aussi je vais raconter ma vie avec vous :)
Et oui, il doit deja deseperer :)
