### ISSUE TITLE
Style CSS

### ISSUE THREAD

**Issue by defeo** [in202-uvsq/git-manual#11]
Travailler sur le fichier `css/style.css`, commun à toutes les pages.

Assigné à: @ducks-skills , @in202-uvsq/2015-release-manager

**Comment by Nambrok** [comment]
@ducks-skills Tu devrais peut-être utilisé des classes pour les différents cas comme [ici](https://github.com/in202-uvsq/git-manual/blob/gh-pages/commandes/git_checkout.html)?

**Comment by ducks-skills** [comment]
Ouais de toutes manière je t'envoie ce que j'ai fait d'ici 1-2h

**Comment by Nambrok** [comment]
Cool merci :+1:

**Comment by ducks-skills** [comment]
De rien tu veux un screen en attendant ? :smile:

**Comment by Nambrok** [comment]
Je te fais confiance (de toute façon je suis un très mauvais designer ^^)

**Comment by ducks-skills** [comment]
ok bah moi j'ai fait un petit truc vite fait la on verra ce que vous en pensez

**Comment by ducks-skills** [comment]
voila j'ai fait un pull request

**Comment by Nambrok** [comment]
Ok je l'ai merge.

**Comment by Nambrok** [comment]
Par contre, pourrait tu mettre le css dans un dossier css stp.

**Comment by ducks-skills** [comment]
ok je m'en occupe, sinon les couleurs tout ca ca va ?

2015-03-08 17:35 GMT+01:00 Nambrok <notifications@github.com>:

> Par contre, pourrait tu mettre le css dans un dossier css stp.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/in202-uvsq/git-manual/issues/11#issuecomment-77759645>
> .
>



-- 
C.Briand

**Comment by Nambrok** [comment]
Oui c'est bien les couleurs, faudrait voir avec les autres si ça leur plait ;)
Faudrait aussi leur donner les changements à effectuer sur leur page pour qu'ils charge le css (je met ça sur le [wiki](https://github.com/in202-uvsq/git-manual/wiki/Squelette.html)).

**Comment by Nambrok** [comment]
Voilà j'ai fait les modifications de la ligne qui permet de charger le css pour qu'elle marche pour les commandes se situant dans le dossier des commandes quand le css est dans son propre dossier.

**Comment by Nambrok** [comment]
@ducks-skills Tu as mis en ligne la dernière version du css ?

**Comment by ducks-skills** [comment]
Je rentre du foot la je fait ça dans l soirée mais y a que feux trois trucs
qui vont changer

**Comment by Nambrok** [comment]
Ok
