### ISSUE TITLE
git push et git pull

### ISSUE THREAD

**Issue by defeo** [in202-uvsq/git-manual#15]
Décrire les commandes `git push` et `git pull`. Décrire en particulier les options

- `git pull --rebase`
- `git pull --ff-only`
- `git pull --no-commit`
- `git pull --no-ff`
- `git push -n`
- `git push --tags`
- `git push -f`

Assigné à : @afwanito92 , @amendiI , @Gruudu

**Comment by amendiI** [comment]
je m'occupe de mettre le .html en ligne depuis : https://github.com/amendiI/git-manual

**Comment by afwanito92** [comment]
oups dsl je viens  de voir ce msg !!
g une journée de retard lol 
je vais faire le git push -f et le git push --tags

**Comment by amendiI** [comment]
je m'occupe de:
git pull --rebase
git pull --ff-only
git pull --no-commit

il faudrait que tu fasse une commande supplémentaire afwanito.
et gruudu tu peux t'occuper de git pull --no-ff et des descriptions générales  des commandes pull et push stp ?

**Comment by afwanito92** [comment]
je suis desolé mais la console ne fonctionne plus che mwa :( :( donc est ce que ce serait possible que l'un de vous mettes les exemples a afficher  svp 
?? merci d'avance

**Comment by afwanito92** [comment]
je suis desolé mais la console ne fonctionne plus che mwa :( :( donc est ce que ce serait possible que l'un de vous mettes les exemples a afficher  svp 
?? merci d'avance

**Comment by afwanito92** [comment]
je suis desolé mais la console ne fonctionne plus che mwa :( :( donc est ce que ce serait possible que l'un de vous mettes les exemples a afficher  svp 
?? merci d'avance

**Comment by afwanito92** [comment]
je suis desolé mais la console ne fonctionne plus che mwa :( :( donc est ce que ce serait possible que l'un de vous mettes les exemples a afficher  svp 
?? merci d'avance

**Comment by afwanito92** [comment]
je suis desolé mais la console ne fonctionne plus che mwa :( :( donc est ce que ce serait possible que l'un de vous mettes les exemples a afficher  svp 
?? merci d'avance

**Comment by afwanito92** [comment]
je suis desolé mais la console ne fonctionne plus che mwa :( :( donc est ce que ce serait possible que l'un de vous mettes les exemples a afficher  svp ?? merci d'avance

**Comment by afwanito92** [comment]
je suis desolé mais la console ne fonctionne plus che mwa :( :( donc est ce que ce serait possible que l'un de vous mettes les exemples a afficher  svp ?? merci d'avance

**Comment by afwanito92** [comment]
je suis desolé mais la console ne fonctionne plus che mwa :( :( donc est ce que ce serait possible que l'un de vous mettes les exemples a afficher  svp ?? merci d'avance

**Comment by afwanito92** [comment]
je suis desolé mais la console ne fonctionne plus che mwa :( :( donc est ce que ce serait possible que l'un de vous mettes les exemples a afficher  svp ?? merci d'avance

**Comment by amendiI** [comment]
STOP SPAM !!!
la console ne marche pas chez moi non plus et gruudu ne répond pas...

**Comment by Gruudu** [comment]
Pardon de me réveiller aussi tard pour faire ça mais il faut bien que je fasse le pull, le push et le pull --no-ff ? Mais je ne comprend pas pourquoi il y a un déjà un doc html dans le projet final cela veut dire que vous avez fait un pull request qui a été accepté ?

**Comment by amendiI** [comment]
un réveil plus que tardif... un peu plus et je me reconnectais pas. le fichier n'est pas fini, mais je l'ai quand même envoyé.
je fait le dernier pull request a 19h30, essaye de finir ta partie avant.

**Comment by Gruudu** [comment]
J'ai fini ma partie par contre je ne sais pas comment je te "l'envoi"

**Comment by amendiI** [comment]
tu dois modifier le fichier dans mon fork. Tu a les droits de modification.

**Comment by Gruudu** [comment]
C'est bon ?

**Comment by amendiI** [comment]
oui, j'envois le pull request

**Comment by Gruudu** [comment]
Ok cool, encore désolé pour le retard !
