### ISSUE TITLE
git merge

### ISSUE THREAD

**Issue by defeo** [in202-uvsq/git-manual#16]
Décrire la commande `git merge`. Décrire en particulier les options

- `git merge --no-commit`,
- `git merge -ff-only`,
- `git merge --squash`,
- `git merge -m`,
- `git merge --abort`.

Assigné à : @calae91, @cricri3007 , @incognitomada

**Comment by cricri3007** [comment]
Qui fait quoi ?

**Comment by Misscouettes** [comment]
Bonjour, je voulais juste savoir si vous aviez un problème ou non, car vous n'avez fait aucun pull request. On en a besoin, même si vous nous envoyez un squelette non remplit, pour faire l'index.html (nom du fichier et voir si vous êtes sur la bonne voie).

**Comment by calae91** [comment]
Bonsoir mis à jour se soir je n'ai pas pu être présent et je m'en excuse.

Veuillez suivre le lien suivant et travaillez sur vos commandes : https://github.com/calae91/git-manual

Si possible à faire le plus rapidement possible afin que je puisse vérifier et pouvoir remédier à certains problèmes qui pourraient venir.

Idem que pour mon autre groupe je me permet de faire le partage du travail entre nous 3.

cricri3007 devra prendre en charge : 
-git merge --squash

incognitomada devra prendre en charge : 
-git merge -m
-git merge -ff-only

Je me charge du : 
-git merge --no-commit
-git merge --abort

**Comment by calae91** [comment]
Je vous ai ajouté en tant que collaborateur afin que vous puissiez avoir accès aux fichiers. Bon courage :)

**Comment by calae91** [comment]
bonjour j'aimerais savoir si @cricri3007 ou @incognitomada  rencontre des problèmes sur sa tache, pas de réponse mais il faudrait le faire pour mercredi afin de faire un bon gros pull request.

Merci d'avance :+1:

**Comment by cricri3007** [comment]
Désolé de ne pas avoir répondu plus tôt.
Je m'en occupe ou ce soir ou demain matin.

**Comment by incognitomada** [comment]
Salut c'est fait. Vous avez bien reçus mes modifications pour -git merge -m et -git merge -ff-only ?

**Comment by calae91** [comment]
oui ! en effet tout m'a l'air correct !
Je fais le regroupement de dossier en ce moment :)

**Comment by calae91** [comment]
Bon je viens de terminer la mise en page de chaque option, si vous pouvez regarder afin de voir si je n'ai pas fais de fautes d'orthographe ou de mauvaise mise en page.

**Comment by Misscouettes** [comment]
Yop, vous avez fini ici ?

**Comment by calae91** [comment]
oui @Misscouettes c'est bon ^^
