### ISSUE TITLE
git reset

### ISSUE THREAD

**Issue by defeo** [in202-uvsq/git-manual#17]
Décrire la commande `git reset`. Décrire en particulier les options

- `git reset --soft`
- `git reset --mixed`
- `git reset --hard`
- `git reset --keep`

Assigné à : @chaouki08, @Iwantaponey, @KaneBoubacar , @ThomasBrebant .

**Comment by Iwantaponey** [comment]
Qui fait quoi ?
Je veux bien faire git reset --soft  et m'occuper des pull request, donc en forkant le repertoire de la classe.
Du coup, vous devriez forker sur moi ensuite pour continuer à modifier 

J'espère que ça vous va, hésitez pas à me dire sinon.

**Comment by Iwantaponey** [comment]
en fait je crois que je ne peux pas, parce que j ai déjà forké un autre répertoire...
donc mieux vaut que quelqu'un d'autre fork !
J'ai fini git reset --soft.

**Comment by KaneBoubacar** [comment]
Yo,

Je viens de vous pull request la page git reset
Vous verrez que c'est bien vide...

Si quelqu'un connait un site ou les commandes sont expliquées en français, car quand j'utilise git help, ça me l'affiche en anglais et j'ai un peu de mal.

(Vous allez aussi recevoir la page git commit, accessoirement)

N'hésiter pas à faire le pull request en fin de journée pour la personne s'occupant de l'index.

Bonne journée,

**Comment by Iwantaponey** [comment]
Hey, 
Merci pour la request, je viens de finir git reset --soft
Pour ma part je traduis les informations de "git help reset" puis je cherche sur le net pour avoir plus d'infos si nécessaire.
Voilà, je vais faire une pull request je pense
++

**Comment by Iwantaponey** [comment]
Au fait, j'ai supprimé git commit de mon répertoire avant de faire la pull request.
Et aussi, petit truc : on utilise un id qu'une seule fois. Sinon, on utilise des class.
J'ai corrigé git reset du coup.
Voilà, j'attends que tout le monde ait choisi et fini une partie.
Tchao.

**Comment by ThomasBrebant** [comment]
Je m'occupe de git reset --hard si cela vous va.

**Comment by Iwantaponey** [comment]
Très bien, n'oublie pas de forker ton git reset depuis mon répertoire avant TOUTE modification : 
https://github.com/Iwantaponey/git-manual/blob/gh-pages/commandes/git_reset.html

De plus, une fois ta commande achevée, il faudra que tu me fasses une pull request.

**Comment by Iwantaponey** [comment]
@Misscouettes  Hey ! C'était pour savoir si vous étiez satisfaits de ce qu'on avait déjà fait sur cette commande :)

**Comment by KaneBoubacar** [comment]
J'ai pris --mixed

**Comment by Iwantaponey** [comment]
Il y a un problème @KaneBoubacar  Tu dois pull mes modifications (notamment le nom du fichier qui ne correspond pas) avant de push !
J'obtiens des conflits non résolvables, tu dois résoudre ce problème

**Comment by Misscouettes** [comment]
Bah ça a pas l'air trop mal, on a accepté votre pull request et je vois que ça avance bien. Mais c'est vrai qu'il ne faut pas oublier toujours de pull avant de push, sinon après vous avez des conflits (mais je crois que pour ceux là il suffit d'effacer le morceau de code qui ne va pas)

**Comment by Iwantaponey** [comment]
@KaneBoubacar  où en es-tu ?

**Comment by KaneBoubacar** [comment]
Quand je pull ton repertoire ( en mettant l'url ) ça pull directement le miens.
Je vois pas comment faire plus.

**Comment by Iwantaponey** [comment]
essaye ça
"git remote add principal https://github.com/Iwantaponey/git-manual"
"git pull principal gh-pages" 
"git push origin

**Comment by Iwantaponey** [comment]
puis modifie git_reset avec ta commande, fais git add git_reset.html, git commit -m "git reset --mixed" refais git push origin
puis fais un pull request

**Comment by Iwantaponey** [comment]
le pull request doit etre fait sur github, tout le reste dans le terminal

**Comment by KaneBoubacar** [comment]
Je sais,
C'est exactement les commandes que j'ai entré.
Mais quand je fais le "push", le terminal me renvoie "everything up to dates" justement parce que ce qui est pull est mon répertoire et pas le tiens.

J'ai essayé de créer un nouveau dossier, supprimer totalement le miens... mais je comprends pas ou j'ai fais la mauvaise manip'

**Comment by KaneBoubacar** [comment]
J'ai modifié la page html sur le site git depuis ton répertoire, du coup ça a fais la proposition de changement sous forme de pull request si j'ai bien compris, je pense que tu devrais pouvoir accepter le pull request.

**Comment by Iwantaponey** [comment]
@ThomasBrebant  où en es-tu ?

**Comment by Iwantaponey** [comment]
@chaouki08 où en es-tu ?

**Comment by ThomasBrebant** [comment]
C'est normal que la mise en page déconne ?

**Comment by Iwantaponey** [comment]
j ai tout mis bien normalement

**Comment by Iwantaponey** [comment]
@in202-uvsq/2015-release-manager J AI FINI

**Comment by Misscouettes** [comment]
Tout est bien bien ?

**Comment by Misscouettes** [comment]
@Nambrok y'a un problème ici au lvl de l'affichage de git reset sur le site HTML. Ça vient du squelette non ?

**Comment by Misscouettes** [comment]
Tout est parfait merci Julie :)
