### ISSUE TITLE
git rebase

### ISSUE THREAD

**Issue by defeo** [in202-uvsq/git-manual#18]
Décrire la commande `git rebase`. Décrire en particulier les options

- `git rebase --onto`,
- `git rebase -i`,
- `git rebase --continue` et `git rebase --abort`,

Assigné à : @Lebataclan, @LowD , @Mr-Nico-972

**Comment by Lebataclan** [comment]
yop, donc qui fait quoi? et faudrait qu'on se fasse un répertoire commun donc qui est ce qui l'heberge?

**Comment by Mr-Nico-972** [comment]
je peut faire git rebase --continue et git rebase --abort si il n'y pas de probleme

**Comment by LowD** [comment]
Je peux faire git rebase -i et git rebase --onto.

**Comment by celinec** [comment]
Bonjour, je voudrais savoir si vous rencontrez un quelconque problème dans la création de vos pages HTML car nous n'avons eu aucun pull request de votre part et n'avons aucune nouvelle. 
Je vous rappelle qu'il nous faudrait au moins un pull request d'ici ce soir (même si vos fichiers sont toujours incomplets) afin de voir si vous avez des problèmes pour faire ces pull request, pour qu'on puisse vous aider sans devoir s'y prendre à la dernière minute.
La foire aux questions nous permettra de vous répondre

**Comment by Lebataclan** [comment]
euh... ouais mais du coup moi je fais rien la... si y'en a au moins un qui me file une fonction de git rebase ce serait cool

**Comment by Mr-Nico-972** [comment]
sinon tu peut heberger au pire nan ??

**Comment by Mr-Nico-972** [comment]
jte passe git rebase --abort si tu veux ??

**Comment by Mr-Nico-972** [comment]
faut aussi decrire git rebase

**Comment by Lebataclan** [comment]
okay donc je viens de créer le git rebase

**Comment by Lebataclan** [comment]
@LowD merci pour ton merge

**Comment by Lebataclan** [comment]
@Mr-Nico-972 Il te rest plus qu'une 1h30, tu veux bien faire ta partie pour que je puisse faire le pull request final? parcequ'il reste plus que toi la

**Comment by LowD** [comment]
Je t'envoie les exemples que je viens de finir.

**Comment by Mr-Nico-972** [comment]
ok jvien de rentrer chez moi javais sport mais j'ai bientot fini et jt envoie git rebase --continue dans quelques minutes

**Comment by Mr-Nico-972** [comment]
je sais pas pour l'exemple

**Comment by Mr-Nico-972** [comment]
ya que ca qu manque

**Comment by Lebataclan** [comment]
file je le ferai

**Comment by Misscouettes** [comment]
Yop, vous vous en sortez ?

**Comment by Lebataclan** [comment]
@Misscouettes yop ouais, j'attends juste le pull request de nico et je vous envoie le miens

**Comment by Misscouettes** [comment]
Okey

**Comment by Lebataclan** [comment]
@Mr-Nico-972 envoie ton pull request je reglerais le reste

**Comment by Mr-Nico-972** [comment]
@Lebataclan jlai fait la nan ??

**Comment by Mr-Nico-972** [comment]
di moi si t'as recu quelque chose

**Comment by Lebataclan** [comment]
nan j'ai rien reçu

**Comment by Mr-Nico-972** [comment]
putain sa me fait chier

**Comment by Lebataclan** [comment]
c'est bon

**Comment by Mr-Nico-972** [comment]
ah ok enfin !!!!!!!

**Comment by Lebataclan** [comment]
par contre tu as fait un pull request mais comme la page était dans les commandes elles ont pas merge ensemble et je dois le faire donc je vais essayer de le dire au prof demain pour pas qu'il croit que tu as rien fait

**Comment by Mr-Nico-972** [comment]
ah ok d'accord j'galère trop merci

**Comment by Lebataclan** [comment]
@in202-uvsq/2014-2015 fini, désolé pour le retard

**Comment by Mr-Nico-972** [comment]
t'a géré heureusement que t'es la :)

**Comment by Lebataclan** [comment]
@Mr-Nico-972  Naaah tkt on a tous fait notre boulot ^^
