### ISSUE TITLE
git clone et git init

### ISSUE THREAD

**Issue by defeo** [in202-uvsq/git-manual#19]
Décrire les commandes `git clone` et `git init`. Décrire en particulier les options

- `git clone -b`,
- `git clone -o`,
- `git clone --single-branch`,
- `git init --bare`, `git clone --bare`.

Détailler le concept de *répertoire nu* (*bare repository*).

Assigné à : @MaxouUVSQ , @moumzy, @Protosspaspris .

**Comment by moumzy** [comment]
Bonjour, je vois c'est qui MaxouUVSQ mais Protosspaspris ?
Faut qu'on definisse un task leader et on a deux choix pour proceder :
1) Le task leader nous donne les droit d'écriture sur son Fork.
2) On travaille chacun sur son Fork et on envoie une pull request au Leader.

ps: faut qu'on discute un maximum sur ce canal de notre progression.

**Comment by moumzy** [comment]
Je veux bien m'occuper de git clone , git clone -b et git clone -o

**Comment by Misscouettes** [comment]
Bonjour, je voulais juste savoir si vous aviez un problème ou non, car vous n'avez fait aucun pull request. Je vois que vous venez de commencer, alors quand vous aurez choisit qui fait quoi et votre Task leader etc, faites un petit pull request histoire qu'on puisse commencer à faire l'index et qu'on sache où vous en êtes.

**Comment by Protosspaspris** [comment]
je m'occupe de git init bare et git clone bare

**Comment by MaxouUVSQ** [comment]
Je m'occupe de git --clone-single-branch.
Je suis le task leader

**Comment by MaxouUVSQ** [comment]
Re, au final on s'est organisés à la bu, c'est tibault le task leader

**Comment by MaxouUVSQ** [comment]
J'ai commit mes changements dans le fork de moumzy.
Quelqu'un peut checker ce que renvoie git clone --single-branch dans un terminal svp ? J'ai pas de linux sous la main

**Comment by moumzy** [comment]
Bonsoir,
On a plusieurs problèmes et il reste une heure :
- MaxouUVSQ doit s'occuper de git init (description de la commande générique) car tu t'occupe que d'une commande alors que moi j'en ai 3 et ProtossPaspris 2.
- J'ai aucune nouvelle de ProtossPaspris , il a l'acces a mon répertoire mais aucun changement. Si je peux avoir ton numéro pour aller plus rapidement..
- J'ai fini avec mon autre groupe donc la je peux pleinement consacrer l'heure qui reste ici.
Tel : 0667378251

Pour info j'ai deja fais un premier pull request vide donc l'a j'attend vos modifications ou au moins un coup de tel pour voir.

**Comment by MaxouUVSQ** [comment]
Je viens de voir ton message, j'avais pas capté qu'il y avait git init, tu l'auras à temps.
Sympa la sortie ? T'as chopé la demoiselle ?

**Comment by Protosspaspris** [comment]
je go pour git init bare et git clone bare

**Comment by Misscouettes** [comment]
Yop, vous vous en sortez ?

**Comment by Protosspaspris** [comment]
on peut pas vraiment dire ca

**Comment by Misscouettes** [comment]
Qu'est-ce qu'il se passe pour vous ?

**Comment by MaxouUVSQ** [comment]
J'ai commit git init

**Comment by moumzy** [comment]
Sa va être chaud pour cloturer a 20h car on a pris du temps on sa contacter. 20h30 sa devrait être ok !(j'ai finis mon UE a 17h30 le temps de rentrer 18h30) ..

**Comment by moumzy** [comment]
J'ai besoin que tu me contact par téléphone Protosspaspris. 
Quand finira tu ? Si c'est le cas dit moi.
Pour MaxouUVSQ c'est ok

**Comment by Misscouettes** [comment]
Moi je suis ok, après le prof tout ça etc je sais pas trop

**Comment by moumzy** [comment]
J'ai mis un message dans le canal avec le prof. 
Je vais pas faire un pull request alors que j'ai pas tout ... si ?

**Comment by Misscouettes** [comment]
Comme presque tout le monde a fini, 30 min de retard ça devrait passer

**Comment by Protosspaspris** [comment]
j'ai fait le git init bare,vous pouvez le forker

**Comment by moumzy** [comment]
Apelle moi parce que sa tourne au carnage la .

**Comment by moumzy** [comment]
Si tu m'appelle pas je prend pas la responsabilité des futures erreur.
MaxouUVSQ n'est pas ok enfaite il a oublier de prendre la derniere version du squelette html donc je dois reprendre.
Protosspaspris Tu a écrit sur mon Fork a moi j'espere ?! Je t'ai donner les droit d'écriture pour sa.

**Comment by Misscouettes** [comment]
Il n'y a que le git clone --bare pour le moment qui a été pull request

**Comment by Misscouettes** [comment]
Et le git init-bare
