### ISSUE TITLE
git add et git rm

### ISSUE THREAD

**Issue by defeo** [in202-uvsq/git-manual#2]
Décrire les commandes `git add`, `git rm` et `git mv`.

Décrire en particulier les options

- `git add -i`
- `git add -f`, `git rm -f`, `git mv -f`
- `git add -n`, `git rm -n`, `git mv -n`.

Assigné à : @afwanito92, @chaouki08, @calae91

**Comment by calae91** [comment]
git add -i et git add -n pour moi

**Comment by chaouki08** [comment]
git add et git rm pour moi

**Comment by afwanito92** [comment]
git add -f pour mwa !!!

**Comment by calae91** [comment]
http://git-scm.com/docs/git-add

**Comment by defeo** [comment]
Je m'excuse, j'ai oublié d'inclure la commande `git mv` dans cette issue, je viens d'éditer la description. Bon, ce n'est rien de bien compliqué, ça prend quelques lignes à décrire. Les options pour `add`, `rm` et `mv` sont identiques.

**Comment by Misscouettes** [comment]
Bonjour, je voulais savoir où vous en etiez pour savoir si il y a un problème ou si tout se déroule bien (étant donné que afwanito92 a essayé d'envoyer son fichier tout seul). Est-ce que l'un de vous a bien fait un fetch et est-ce que les autres membres du groupe ont fait un clone de ce fichier pour ainsi en avoir un global ?

**Comment by calae91** [comment]
Bonsoir mis à jour se soir je n'ai pas pu être présent et je m'en excuse.

Veuillez suivre le lien suivant et travaillez sur vos commandes : https://github.com/calae91/git-manual

Si possible à faire le plus rapidement possible afin que je puisse vérifier et pouvoir remédier à certains problèmes qui pourraient venir.

**Comment by calae91** [comment]
je me charge en plus de la commande mv ^^

**Comment by afwanito92** [comment]
bah ecoute je viens de mettre la commande git add -f en esperant qu'il est bon mais par contre pour l'exemple j'ai pas reussi a trouver !!

**Comment by calae91** [comment]
je verrais ça demain alors si tu peux le c/c sur ma page afin de tout rassembler ce serait top :)

**Comment by calae91** [comment]
Je vous ai ajouté en tant que collaborateur afin que vous puissiez avoir accès aux fichiers. Bon courage :)

**Comment by afwanito92** [comment]
voila g modifié git add -f dans ton repertoire !!
tiens moi au courant si jamais t'a besoin d'aide 
bon courage !!

**Comment by calae91** [comment]
merci !

**Comment by calae91** [comment]
bonjour j'aimerais savoir si chaouki08 rencontre des problèmes sur sa tache, pas de réponse mais il faudrait le faire pour mercredi afin de faire un bon gros pull request. 

Merci d'avance :+1:

**Comment by calae91** [comment]
j'aimerais savoir si vous aviez un site à me conseiller pour trouver des infos sur le merge je ne trouve as grand chose est c'est souvent sous la forme du merge seulement.

@defeo

**Comment by defeo** [comment]
http://git-scm.com/book/fr/v1/Les-branches-avec-Git-Brancher-et-fusionner%C2%A0%3A-les-bases

`git help merge`

**Comment by calae91** [comment]
en effet je pensais qu'il y avais un tiret, merci !

**Comment by calae91** [comment]
Bon je viens de terminer la mise en page de chaque option, si vous pouvez regarder afin de voir si je n'ai pas fais de fautes d'orthographe ou de mauvaise mise en page.

**Comment by Misscouettes** [comment]
Yop, c'est fini ici ou il vous reste deux trois trucs ?

**Comment by calae91** [comment]
oui @Misscouettes c'est bon ^^
