### ISSUE TITLE
git diff et git blame

### ISSUE THREAD

**Issue by defeo** [in202-uvsq/git-manual#20]
Décrire les commandes `git diff` et `git blame`. Décrire en particulier les options

- `git diff --cached`
- `git diff --stat`
- `git blame -L`,
- `git blame --reverse`,

Assigné à : @Melanie13340, @SuzanneAir, @Ylen96 .

**Comment by Melanie13340** [comment]
Qui veut faire quoi? Perso ça m'es egale

**Comment by Ylen96** [comment]
Ben deja faut créer un répertoire si on veut s'échanger les fichiers, si on a Ca ensuite on peut se répartir les sous parties je pense

**Comment by Ylen96** [comment]
Bonsoir j'ai créer un répertoire git-manual-20 et vous est ajouter aux callaborateurs

**Comment by Ylen96** [comment]
J'ai creer le repertoire separement du git-manual de l'organisation parce-que je n'arrive pas a recuperer quoi que ce soit directement, je pense que il nous permettra dans un premier temps au moins de faire des echanges et de faire les description demandé

**Comment by Ylen96** [comment]
bonjour a votre avis il faut faire une ou 2 pages ? 
(une --> git diff  & git blame) (2 --> git diff --> git blame)

**Comment by Ylen96** [comment]
bon j'ai mis deux pages html au pire on les fusionnera et le squelette est bon donc voil a..

**Comment by Melanie13340** [comment]
Completement HS je viens de voir ta photo de profil :'D 
Sinon il faut que tout soit sur la meme page.. Donc voila, je vais recup tes fichiers mais qui fais quoi du coup?

**Comment by Ylen96** [comment]
qui fait quoi ben deja qu'on reussise a envoyer les fichier avec le titre et le squellette ce sera un grand pas :')

**Comment by Melanie13340** [comment]
Si on etait 3 au lieu de 2 à en discuter aussi ce serait cool! ^^ Je vais cheker ca, moi j'ai reussis a envoyer les trucs sur l'u=autre repertoire

**Comment by Melanie13340** [comment]
Bah c'est bon, les trucs sont dans commandes!

**Comment by SuzanneAir** [comment]
désolée j'étais occupée tout le week-end ! donc si j'ai bien compris c'est ylène qui se charge de la copie du dossier, et donc on doit la forker ? j'avoue je comprend pas tout...

**Comment by Melanie13340** [comment]
Moi non plus

**Comment by Ylen96** [comment]
alors c'est simple j'arrive pas a faire la copie du dossier ayant deja la gh-pages de l'autre groupe auquel j'appartiens sur mon ordi donc je sais pas trop comment faire , par contre le repertoire independant auquel vous etes toutes les deux collaboratrice est la copie exacte de se que on doit rendre sauf que ben c'est un repertoire EXTERNE ... qui contient ce qu'il faut envoyer mais pas de gh-pages = pas de pull request ou sinon je sais pas comment on fait

**Comment by celinec** [comment]
Bonjour, je voudrais savoir si vous rencontrez encore un problème dans la création de vos pages HTML.
@Ylen96 tu as tenté deux pull request non conformes. Je serai tentée de te proposer de refaire ton dossier commande en repartant de zéro ou de faire un git reset pour retourner à un commit où tu n'avais pas de problème avec le fichier git reset, qui n'est pas sensé être fait par ton groupe d'ailleurs, lorsque tu avais uniquement tes deux fichiers git blame et git diff afin de nous les envoyer pour qu'on ait déjà une base et que l'index soit faisable

**Comment by Ylen96** [comment]
Je viens de tenter de renvoyer une pull request le fichier git- reste est toujours la mais j'ai recopier le code exacte que vous avez du reste pour éviter les conflit j'attend de voir si ça marche cette fois 

Y. ABOULFATH

**Comment by SuzanneAir** [comment]
bon je commence à peu près saisir ce qu'on doit faire (le temps que mon cerveau percute un peu) 
mélanie et moi on doit forker ylene, cloner le dossier, et ensuite pull request ce qu'on a fait vers ylen, qui fera un pull request vers l'original. logiquement c'est faisable. donc qui se charge de quoi ? perso je vais prendre euh.... git diff --cached et git diff --stat ça a l'air marrant ^^ (enfin si ça vous embête dites le moi je ferais autre chose) et après on va gérer à ce niveau ! courage les filles !

**Comment by Ylen96** [comment]
@celinec j'ai tout repris à zero et re fait un fork et renvoyer une pull request avec 3 fichier donc voilou
@SuzanneAir  pr echanger les fichier l'utilisation du repertoire externe "git-manual-20" auquelleq je t'ai ajouté en collaboratrices devrait etre le plus pratique et si tu t'occupe de git diff on se partagera les git blame avec @Melanie13340 
bonne soiree

**Comment by celinec** [comment]
Nickel ton pull request merci Ilène ;)

**Comment by Melanie13340** [comment]
Du coup partageons nous les blame ^^

**Comment by Ylen96** [comment]
@Melanie13340 à toi l'honneur du choix ^^
btw pour la gh-pages clic sur fork (dans l'organisation in202/git-manual) et ça devrait te créer ta branche gh-page ensuite tu clone sur l'ordi sa devrait avoir cette tête = 
git clone https://github.com/Melanie13340/git-manual
et ensuite ben classique add commit blablabla 
et pour faire la pull request si tu n'y arrive pas avec powershell passe par github directement des que tu vois ça écrit tu clique et tu met in202 en base et Melanie 13340 sur l'autre
voilou

**Comment by Ylen96** [comment]
@SuzanneAir  il faudras que tu fork mon repertoire git-manual-20, tu auras le squelette pret de la page git-diff et plus facile pour recuperer le fichier si tu veux que je fasse la pull request finale sinon tu devras la faire

**Comment by Ylen96** [comment]
Y. ABOULFATH

**Comment by Melanie13340** [comment]
Ca me met (avec in-202 en base et Moi en head) : There isn't anything to compare.

in202-uvsq:gh-pages is up to date with all commits from Melanie13340:gh-pages. Try switching the base for your comparison.

i'm lost,j'ai tout tente, avec powershell, sur le site..

**Comment by Melanie13340** [comment]
@Ylen96 Bon, j'ai commence à explique ce que c'etait Blame & Blame -L :) J'envois tout bientot sur le repertoire pour que tu recupere ce que j'ai fais ;)

**Comment by SuzanneAir** [comment]
@Ylen96 c'est toi qui fait le pull request final on est d'accord. Est ce que tu m'as ajouté en collaboratrice ? Si non peux-tu le faire ? et me donner le droit de modifier des trucs directement sur ta page ? on a fait comme ça avec l'autre groupe et ça marche nickel. Sinon j'ai bien avancé sur git diff. Je termine là et on s'arrange pour que je te l'envois. ça marche ?

**Comment by SuzanneAir** [comment]
je n'ai pas d'exemple pour git diff --cached (je n'ai pas très bien compris comment on s'en servait) c'est grave ?

**Comment by Melanie13340** [comment]
Ylène ne te répondra pas ce soir, elle est comme qui dirait aveugle pour le moment. Normalement tu es en collaboratrice si j'ai bien suivis les événements et pour le pull request elle ne m'en a pas parle. Il faudra que tu vois ça avec elle demain en cours. Si tu veux lui envoyer fais le sur le répertoire qu'elle a créer et vous verrez ça demain. Pour modifier la page qu'elle a fait pour diff normalement tu peux vu que tu es censé être en colab, tu as juste a clone son répertoire! Pour ce que tu n'arrives pas à comprendre essaye de faire des recherches sur internet, car si on nous a demandé ces commandes c'est pour qu'elles y soient toutes.. Je sais que c'est galère mais bon. J’espère que ça t'a aidé. Bonne soirée.

**Comment by SuzanneAir** [comment]
Merci Mélanie ! je vais voir ce que je peux faire ^^ à demain !

**Comment by Ylen96** [comment]
coucou, j'ai mis le squelette a jour sur git-manual-20 (@Melanie13340) enfin ce que j'en est compris soit un copie du wiki ^^ 
aussi @SuzanneAir si ton squelette est bon vas y je ferai le pull request final vers 19h donc si tu as des trucs que tu ne trouve pas n'hesite pas a me les envoyer plus tot pour que j'essaye de completer voilou 
bonne journee

**Comment by Ylen96** [comment]
@Melanie13340 @SuzanneAir tout les fichier son sur ma gh-pages et sur le repertoire git-manual-20, n'hesitez pas je completerai mes parties hors des repertoire pour eviter x ou y croisement n'hesitez pas .

**Comment by SuzanneAir** [comment]
merci @Ylen96 ! je pense que j'aurais terminé d'ici une heure environ

**Comment by Melanie13340** [comment]
Du coup j'ai un truc a modifie?

**Comment by SuzanneAir** [comment]
alors @Ylen96 j'ai besoin de savoir comment tu as réussi ton pull request parce que je galère depuis 13h30 pour gérer ça !

**Comment by Ylen96** [comment]
@SuzanneAir alors moi j'ai mis 2 jours a faire le premier pull request --' et au final j'avais fini par opter par totalement supprimer ma gh-pages et tout reprendre a zero  en faisant donc un fork et en reprenant mes fichiers ajout commit push pull request et voila (c'est un peu radical ). après pour le diff tu peux forker le repertoire git-manual-20 que j'ai fait ( et si tu galere vrmt meme par mail si tu veux). bon courage et tiens moi au courant que je puisse faire la derniere pull request a une heure descente :p

**Comment by Ylen96** [comment]
@SuzanneAir  pourrais tu m'envoyer ton fichier dans oas trop longtemp si tu souhaite que je fasse la pull request

**Comment by SuzanneAir** [comment]
finalement j'ai réussi !! alléluia !! merci quand même @Ylen96 ^^ et git diff et git blame c'est bon ?

**Comment by Ylen96** [comment]
ben j'aurais besoin que tu me dise si tu as rajouter des trucs a git-diff et à ce moment la me les envoyer
git blame petit soucis avec l'exemple de git blame --reverse que je n'arrive pas à faire fonctionner sur mon terminal.

**Comment by Ylen96** [comment]
@SuzanneAir  as tu finis le git diff ???? et veux tu que je fasse la derniere pull request si oui envoie moi ton fichier !!!!!!!

**Comment by Misscouettes** [comment]
Alors ici, est-ce que vous avez fini ?

**Comment by Ylen96** [comment]
et bien j'attend @SuzanneAir pour ces mises a jour de git-diff vu qu'elle voulait que je fasse la pull request final, et il ne manque que un exemple pour le git-blame --reverse, mais ni @Melanie13340, ni moi ne parvenont à le faire fonstionner

**Comment by Misscouettes** [comment]
Suzanne dit qu'elle t'a tout envoyé mais manque juste un exemple pour git cached qu'elle n'a pas réussit à utiliser

**Comment by Ylen96** [comment]
ben je vais le faire dessuite à l'heure mais j'etais pas au courant ....

**Comment by Misscouettes** [comment]
C'est pas grave :)

**Comment by Ylen96** [comment]
J'ai deja fait la pull request de toute façon c'etait juste histoire de bien tout faire..; :D

**Comment by Ylen96** [comment]
et comme personne d'autre n'est la je pense que on peut dire que on a fini

**Comment by Misscouettes** [comment]
Okey
