### ISSUE TITLE
git revert

### ISSUE THREAD

**Issue by defeo** [in202-uvsq/git-manual#21]
Décrire la commande `git revert`. Décrire en particulier les options

- `git revert -e`,
- `git revert -n`,
- `git revert --continue`, `git revert --abort`.

Assigné à : @stefou , @yobero , @pierre-cauletUVSQ

**Comment by yobero** [comment]
qui fait quoi ?

**Comment by yobero** [comment]
je vais m'occuper de git revert et git revert -e

**Comment by pierre-cauletUVSQ** [comment]
D'accord. Je me lance sur git revert -n (dans l'ordre).
@stefou peux-tu traiter des commandes git revert --continue et --abort (j'ai l'impression que les deux sont liés).
Qui sait héberger le repertoire commun sur lequel on fork et on travaille tous ensemble (il faudra donner les droits aux autres membres du groupe). Je peux eventuellement d'ici mercredi, le temps de finir ce que j'ai fais avec le 1er groupe (en peu en bazar...).

**Comment by yobero** [comment]
Tu prends le repertoire commun alros ? si tu veux.

**Comment by yobero** [comment]
La page git-revert.html est sur le repertoire commun

**Comment by yobero** [comment]
@pierre-cauletUVSQ  @stefou Faudrai que vous rajoutiez vos commandes dans la page git-revert.html

**Comment by pierre-cauletUVSQ** [comment]
@defeo Bonjour Monsieur, n'ayant pas pu prendre contact avec @stefou , que devons nous faire des commandes qu'il devait traiter ? (sachant que je n'ai pas accès à git chez moi, je pourrai uniquement modifier avec internet les commandes, sans fournir d'exemples).

**Comment by defeo** [comment]
Laissez en blanc et grondez-le quand vous le voyez.

**Comment by pierre-cauletUVSQ** [comment]
J'ai terminé git revert -n et je te laisse vérifier rapidement si tout correspond pour ensuite faire le pull request. Fait moi savoir si tu as besoin d'aide Yoann.

**Comment by yobero** [comment]
@pierre-cauletUVSQ  Pull request envoyé

**Comment by Misscouettes** [comment]
Yop, c'est fini ici ? Tout est bon ?
