### ISSUE TITLE
git tag

### ISSUE THREAD

**Issue by defeo** [in202-uvsq/git-manual#22]
Décrire la commande `git tag`. Décrire en particulier les options

- `git tag -a`,
- `git tag -d`,
- `git tag -f`,
- `git tag -m`,

Décrire aussi le fonctionnement de la commande `git push --tags`.

Assigné à: @ThomasBrebant .

**Comment by Misscouettes** [comment]
Bonjour, je voulais juste savoir si tu avais un problème ou non, car tu n'as fait aucun pull request. On en a besoin, même si tu nous envois un squelette non remplit, pour faire l'index.html (nom du fichier et voir si tu es sur la bonne voie). Comme tu es seul, ça devrait être plus facile pour toi car tu n'as pas besoin de t'arranger avec d'autres membres pour les clones de fichier, mais si tu as besoin d'aide contacte-nous.

**Comment by ThomasBrebant** [comment]
Oui je suis désolé je n'ai pas pu ce week-end en plus je n'étais pas là ce
vendredi j'ai donc du demander au prof ce qu'il fallait rattraper.. Je fais
ça vite en rentrant ce soir.

**Comment by Misscouettes** [comment]
Okey pas de problème, si tu as besoin d'aide on est là pour ça.

**Comment by Misscouettes** [comment]
Yop, c'est fini ici ?

**Comment by ThomasBrebant** [comment]
Oui c'est bon
