### ISSUE TITLE
commit-ish

### ISSUE THREAD

**Issue by defeo** [in202-uvsq/git-manual#23]
Décrire les différentes façons d'adresser un commit, en particulier:

- son SHA,
- le nom d'une branche,
- un tag,
- un sélecteur de parent `^` ou `~`,
- un sélecteur temporel `@`,
- un sélecteur de chemin `:`.

La référence complète se trouve dans

~~~
git help revisions
~~~

Assigné à : personne.

**Comment by defeo** [comment]
@Nambrok , j'ai l'impression qui tu as essentiellement répondu à ceci ce matin. Si c'est le cas, tu peux fermer l'issue.

**Comment by Nambrok** [comment]
D'accord. Je ferais quand je serai chez moi. 

Envoyé de mon iPhone
