### ISSUE TITLE
Premier pull request avant lundi

### ISSUE THREAD

**Issue by Nambrok** [in202-uvsq/git-manual#25]
Il serait nécessaire que vous effectuez votre premier pull request avant lundi (au plus tard dimanche dans la soirée, pas besoin que votre page soit super avancée mais qu'elle soit au moins nommée (nom_de_votre_commande.html) pour que la personne assignée à l'index puisse travailler. Merci. Nambrok
@in202-uvsq/2014-2015

**Comment by celinec** [comment]
Bonjour à tous, 

Aujourd'hui, plusieurs personnes m'ont posée des questions à propos du squelette et m'ont parlée de difficultés rencontrées pour forker le git-manual et pour se communiquer les fichiers en intragroupe. Je vous invite donc tous à aller lire le wiki qui compte deux pages : l'une expliquant comment doit être créée votre page html, et l'autre expliquant en détails comment forker et communiquer ce que vous avez fait à ceux travaillant avec vous sur une commande.
Si vous avez des questions, vous pouvez utiliser l'issue "Foire aux questions" car vous n'êtes probablement pas les seuls à vous poser une même question.
De plus, j'ai remarqué que plusieurs d'entre vous n'ont pas la deuxième et dernière version du squelette (avec les balises "code"). Or c'est avec cette version que vous devez créer vos pages html comme il est écrit dans la page wiki "Home", afin que le CSS s'adapte à toutes vos pages. Vous devez donc mettre à jour votre fork, cela vous est expliqué dans la page wiki "Forker correctement [...]".

J'espère en avoir aidé certains !

Bonne fin d'après midi,
Céline

**Comment by celinec** [comment]
Bonsoir,

Il y a actuellement cinq groupes qui n'ont fait aucun pull request qui puisse être accepté, ce serait vraiment sympa de la part de ces cinq groupes de nous en faire un assez vite.
Ces cinq groupes sont :
- git add, git rm, git mv  ( @afwanito92 @chaouki08 @calae91 )
- git status, git show ( @moumzy @pierre-cauletUVSQ  @SuzanneAir )
- git merge ( @calae91 @cricri3007 @incognitomada )
- git rebase ( @Lebataclan @LowD @Mr-Nico-972 )
- git clone, git init ( @MaxouUVSQ @moumzy @Protosspaspris )

Merci d'avance !
