### ISSUE TITLE
Foire aux questions

### ISSUE THREAD

**Issue by Misscouettes** [in202-uvsq/git-manual#26]
Si vous avez des questions à propos de tout et n'importe quoi sur GitHub, son utilisation, des bugs, comment mettre en page etc, posez-les ici.

**Comment by yobero** [comment]
Après avoir fait le premier pull request d'une page, je voulais savoir si on pouvait le modifier par la suite ?

**Comment by Nambrok** [comment]
Vous pouvez modifier votre page autant que vous le voulez tant que vous respectez les regles mise en place tel que respecter l'intégrité du squelette et utilisez les balises que l'on vous demande d'utiliser dans les conditions requises.
Oui, vous pouvez modifier votre page vous aurez juste à faire un pull request pour nous transmettre vos modifications. N'oubliez pas de pull depuis in202-uvsq/git-manual avant de transmettre une pull request comme indiqué dans le wiki sur la page "Forker correctement et créer une pull request" dans le section "Mettre à jour votre fork".

**Comment by Melanie13340** [comment]
C'est normal qu'en clonant git-manual je n'ai pas le squellette avec les "code" a la place des "p"?

**Comment by Nambrok** [comment]
Le squelette ne se trouve plus dans git-manual mais sur une page dédié du wiki pour éviter les erreurs où les collaborateurs modifiait le squelette et crée des problemes empêchant les merge automatiques.
Tu peut trouver le squelette à copier-coller [ici](https://github.com/in202-uvsq/git-manual/wiki/Squelette.html).
N'ajouter pas Squelette.html dans vos commits s'ils vous plaient. Vos commits doivent uniquement changer et ajouter vos page html de votre(vos) commande(s) dans le dossier des commandes.

**Comment by Ylen96** [comment]
@Nambrok contrairement à ce que tu as l'air de penser je ne "m'amuse" pas à modifier le fichier des autres la gh-pages ou sont mes fichiers est communes avec un collaborateur de l'issue1 et le fichier git-reset est le sien par conséquent je n'etait meme pas au courant du niveau ou il etait, et donc parceque je ne vais pas "supprimer" le travaille de quelqu'un d'autre.
J'aimerai que vous me proposiez une option car de nombreux commit ont été effectué depuis l'ajout de ce fichier.

**Comment by defeo** [comment]
Si deux pull requests ont des commits en commun, Git saura merger les deux sans difficultés.

Si dont le fichier `git_reset.html` a été ajouté par le **même commit** (même SHA) dans deux pull requests différentes, il n'y a à priori pas de soucis, mais

- @Ylen96 devra attendre que l'autre pull request soit accepté avant de voir la sienne acceptée,
- Si l'autre pull request est refusée, @Ylen96 devra revenir en arrière pour éviter des conflits avec l'auteur de `git_reset.html`.
- Ce n'est pas une bonne pratique : les commits de @Ylen96 n'ont pas raison de dépendre de ceux d'une autre issue.

La solution c'est de travailler sur `git_reset.html` dans une branche ou un clone différent du reste.

**Comment by Nambrok** [comment]
@in202-uvsq/2014-2015 Une modification importante que vous devriez faire sur vos pages html est la modification du chemin vers le css, vous pouvez la trouver sur le [wiki](https://github.com/in202-uvsq/git-manual/wiki/Squelette.html).
Il suffit de mettre cette ligne ` <link href="../css/style.css" rel="stylesheet" type"text/css"> ` à la place de l'ancienne dans le head de votre page html.

**Comment by Melanie13340** [comment]
Bon, j'expose le probleme, deja c'est en anglais et j'avoue que j'ai du mal a faire les traductions ^^, ensuite pour partager les fichiers avec mes binomes j'ai creer un repertoire, j'ai forker le repertoire ou il faut faire les pull request.. Mais après (et desole pour ceux qui trouveront ca debile) je ne sais pas comment faire, si je pouvais avoir une explication un peu moins technique ce serais cool! Merci :)

**Comment by ducks-skills** [comment]
J'ai fait un guide pour le css cependant il va amener à être modifié :p

**Comment by defeo** [comment]
@in202-uvsq/2015-release-manager cela me semble une mauvaise idée de demander à chaque groupe de faire la modification du chemin vers le fichier css.

Quitte à retarder le changement, il serait plus raisonnable de faire tous ces changements dans un unique commit, assigné à qui vous voulez. Cela rend l'historique plus lisible, et plus facile à défaire le changement.

Vous pouvez attendre d'avoir reçu toutes les pages avant de créer le commits. Cela facilitera les merges, même en cas de conflit. Après avoir fait le changement sur tout le répertoire, vous pouvez imposer le nouveau chemin à tout le monde.

**Comment by defeo** [comment]
Je rappelle à tous qu'il existe une excellente ressource en français http://git-scm.com/book/fr/v1 (et que la lecture de certaines partie est au programme du cours, comme indiqué en amphi).

**Comment by Nambrok** [comment]
Bien, nous effectuerons donc ce changement plus tard.

**Comment by yobero** [comment]
Je ne trouve aucune information sur la commande git fetch -r et elle ne marche pas sur le terminal.

**Comment by calae91** [comment]
elle marche peut être avec certaine condition met ici ce que te réponds le terminal ;)

**Comment by yobero** [comment]
Le prof m'a prévenu que ce n'était pas git fetch -r mais git fetch -t
problème résolu ^^

**Comment by Melanie13340** [comment]
Je ne trouve pas l'explication de la commande branch -u dans le git help..

**Comment by defeo** [comment]
`git branch -u` est la même chose que `git branch --set-upstream-to`.

Et postez ce genre de questions dans l'issue concernée, inutile de surencombrer ce FAQ.

**Comment by Nambrok** [comment]
@in202-uvsq/2014-2015 J'ai mis à jour le [squelette](https://github.com/in202-uvsq/git-manual/wiki/Squelette.html) avec les informations pour que votre page soit compatible avec le css, essayer de comprendre son fonctionnement et n'hésitez pas à poser des questions.

**Comment by yobero** [comment]
@Nambrok Je pense que le lien pour aller dans index.html dans le squelette.

**Comment by Nambrok** [comment]
Oui, c'est vrai, corrigé, merci ;)

**Comment by SuzanneAir** [comment]
je n'ai pas d'exemple pour git diff --cached (je n'ai pas très bien compris comment on s'en servait) c'est grave ?

**Comment by ducks-skills** [comment]
Hum ça serait plutôt cool que tu en ais un parce que ça donnerait comme un manga sans dessins après x)

**Comment by SuzanneAir** [comment]
je sais ! je pense que je n'y arriverai pas ce soir, je vais me reposer, et demain je cherche à fond et je trouverai ! bonne nuit ^^

**Comment by Misscouettes** [comment]
git diff voit ce que tu as modifié, et git diff-cached compare un fichier et le meme fichier avec les modifications que tu viens d'apporter (genre des mots en plus etc). Mais ça ne compare que si tes modifications ne sont pas commité

**Comment by Ylen96** [comment]
bonjour, je suis un peu perdu avec le nouveau squelette, notamment le fait qu'il n'y est plus de titre pour les sous commandes ainsi que les section ? si vous pouviez faire un petit topo ca serait cool

**Comment by Nambrok** [comment]
Il y a un grand titre `<h1> <a href="../index.html"> <img src="../images/logo.png" alt="logo" > </img> </a> <br>Nom de la commande</h1>` pour le titre de la commande(vous devez remplacer Nom de la commande par le titre de la page) et chaque `<section class="descriptif"></section>` contient le descriptif d'une options suivis d'une section `<section class="affichage"></section>` qui montre un exemple.

**Comment by defeo** [comment]
@in202-uvsq/2014-2015 N'oubliez pas de fermer les Issues (bouton Close) lorsque vous avez terminé le travail.

**Comment by SuzanneAir** [comment]
@defeo Bonjour, je n'arrive pas faire un pull request accepté car il y a eu des modifications du squelette, je ne sais pas comment faire en sorte que mon pull request soit accepté.
J'ai essayé de faire un reset d'un clone sur mon ordinateur mais je ne comprend pas comment cela marche, puis j'ai tenté de créer un deuxième répertoire mais impossible de forker deux fois l'in202. Je souhaite seulement faire accepter les deux fichiers de mon groupe mais je ne sais pas non plus faire de nouvelle branche.
Pouvez-vous m'aider?

**Comment by calae91** [comment]
sauvegarde dans un autre dossier le contenue de tes fichiers et supprime ton répertoire. tu pourras re-forker in202 et ajouter en c/c tes dossiers(j'ai eu le même problème et c'est assez radical)

**Comment by defeo** [comment]
@SuzanneAir, une fois que ton répertoire local est dans le bon état, `push -f` pour mettre ton fork github dans le même état.

Il y a plein de façon de mettre le répertoire local dans le bon état : 

- re-cloner,
- reset http://git-scm.com/book/en/v2/Git-Tools-Reset-Demystified
- rebase http://git-scm.com/book/fr/v1/Les-branches-avec-Git-Rebaser
- ...

http://git-scm.com/book/fr/v1/Utilitaires-Git-R%C3%A9%C3%A9crire-l-historique

**Comment by SuzanneAir** [comment]
Merci Monsieur !

**Comment by Ylen96** [comment]
Je n'arrive pas à faire fonctioner git blame --reverse sur mon terminal et je ne trouve aucun exemple?

**Comment by defeo** [comment]
Vieille version de Git ? La doc est ici

  http://git-scm.com/docs/git-blame

ce n'est pas sorcier, une fois que tu sais comment marche `blame`.

**Comment by Ylen96** [comment]
J'ai dejà visité ce site, et j'ai compris la commande, j'arrive parfaitement a faire fonctionner git blame et git blame -L mais --reverse ne fait que me renvoyer des erreurs ce qui m'empeche d'avoir un exemple (c'est l'unique soucis)

**Comment by defeo** [comment]
Comme indiqué dans la doc, `blame --reverse` prend un paramètre en plus (`<rev>`) de la forme `START..STOP`, où `START` et `STOP` sont des identifiants de commits.

**Comment by Nambrok** [comment]
@in202-uvsq/2014-2015 Pourriez-vous nous faire savoir quand le travail qui vous a été assigné dans une issue est terminé en nous "summon"-ant à l'aide de `@in202-uvsq/2015-release-manager` dans l'issue correspondante. Merci

**Comment by moumzy** [comment]
On va être juste pour 20h ! Si on peut avoir une rallonge de 30minute ?! 15 si c,'est non .. :X !
