### ISSUE TITLE
git stash

### ISSUE THREAD

**Issue by defeo** [in202-uvsq/git-manual#3]
Décrire la commande `git stash`.

Décrire en particulier les sous-commandes

- `git stash save`
- `git stash apply`
- `git stash list`
- `git stash show`
- `git stash drop`

Assigné à: @amendiI, @cricri3007, @ducks-skills

**Comment by cricri3007** [comment]
Je m'occupe de stash save et apply, ok ?
Je pense que j'écrit ausi la définition générale de stash, ça vous va ?

**Comment by amendiI** [comment]
je peux faire le stash list et stash show.

**Comment by amendiI** [comment]
je fait aussi le drop

**Comment by cricri3007** [comment]
donc je fait list aussi.

**Comment by amendiI** [comment]
bon, pour le fichier principal je propose ma copie forké:
https://github.com/amendiI/git-manual

**Comment by ducks-skills** [comment]
Okey bon je m'occuperai d'ajouter le css et de corriger vos fautes (il y en aura mouahahah ) sinon après bon boulot ;) A RENDRE MERCREDI SANS FAUTE !

**Comment by amendiI** [comment]
j'ai copié le squelette du html, maintenant je vais grouper, et Christophe ...il n'y a pas la deuxième partie:
 "Puis ce que Git fait, et ce qu'il affiche dans le terminal comme réponse."

**Comment by amendiI** [comment]
je vous laisse aussi noter vos noms sur la page html (dans le footer).
