### ISSUE TITLE
git checkout

### ISSUE THREAD

**Issue by defeo** [in202-uvsq/git-manual#4]
Décrire la commande `git checkout`. Décrire en particulier les options

- `git checkout -m`
- `git checkout -b`
- `git checkout -- <paths>`
- `git checkout -t`
- `git checkout -f`

Détailler les différentes formes de checkout : branche courante, `HEAD` *détaché*, ...

Assigné à: @incognitomada, @Iwantaponey, @Lebataclan

**Comment by Iwantaponey** [comment]
Je propose : 
LeBataclan fait : git checkout -m et git checkout -b
incognitomada fait : git checkout -- <paths> (il existe différents chemins, donc différentes commandes, utilise git help ? )
Je pourrais m'occuper de git checkout -t et de git checkout -f

ça vous va ?

**Comment by Lebataclan** [comment]
oui ça me va( nn je dec)

**Comment by incognitomada** [comment]
ok dans git checkout -- <paths> le paths c'est les différentes commande

**Comment by incognitomada** [comment]
?

**Comment by Iwantaponey** [comment]
Non
en fait
c'est du genre git checkout -- master
git checkout -- <paths> 
je me suis trompée tout à l'heure, désolée
tu peux te servir d'Internet :)

**Comment by Iwantaponey** [comment]
git checkout <paths>

**Comment by Iwantaponey** [comment]
"git checkout < paths >"

**Comment by incognitomada** [comment]
C'est bon http://nicolasgallagher.com/git-checkout-specific-files-from-another-branch/ (y)

**Comment by Iwantaponey** [comment]
Tu pourrais aussi t'occuper du git checkout tout court, sans option ?
Il suffit de faire une petite intro

**Comment by incognitomada** [comment]
Ok comme vous avez deux chacuns c'est plus équilibré

**Comment by Iwantaponey** [comment]
oui :)

**Comment by Iwantaponey** [comment]
Du coup, il faut créer une page gitcheckout.html
Je m'en occupe si vous voulez

**Comment by Lebataclan** [comment]
donc  Iwantaponey et moi on va forker sur ton gitcheckout.html et a chaque fois que l'on va ajouter une  commande et esplication on va faire un pull_request que tu devra accepter ou pas(c'est toi qui vois)

**Comment by incognitomada** [comment]
ok j'accepte directement sur le site ou vec une commande du terminal ?

**Comment by incognitomada** [comment]
C'est bon j'ai trouver ^^

**Comment by Iwantaponey** [comment]
:)

**Comment by incognitomada** [comment]
C'est bon

**Comment by Iwantaponey** [comment]
tu dois faire : 
"git remote add principal https://github.com/Iwantaponey/git-manual"
puis "git pull principal gh-pages" pour télécharger les modifications que j'ai faites.
Ensuite, pour les mettre sur votre interface GitHub, vous faites "git push origin"

**Comment by Iwantaponey** [comment]
@Lebataclan , pas si vite jeune chenapan, il te reste un peu de boulot tout de même ! 
Il faut que tu télécharges les modifications que j'ai faites, puis que tu mettes des exemples pour chaque commande ! 
Je te rappelle que tu avais aussi accepté de faire la partie "Détailler les différentes formes de checkout : branche courante, HEAD détaché..." demandée par le prof.
Bref, bonne fin de week-end :dancer:

**Comment by Iwantaponey** [comment]
@incognitomada  Quand comptes-tu me faire une pull request ? 
Je te rappelle que tu dois décrire la commande générale "git checkout", en donner un exemple puis faire de même avec "git checkout -- <paths>
Avant toute modification, si ce n'est pas déjà fait, tu dois forker ton fichier sur le mien :
https://github.com/Iwantaponey/git-manual/blob/gh-pages/commandes/git_checkout.html

et si c'est déjà fait, tu dois te mettre à jour en utilisant les commandes : 
"git remote add principal https://github.com/Iwantaponey/git-manual"
"git pull principal gh-pages" 
"git push origin"

voilà, bonne journée

**Comment by Iwantaponey** [comment]
@Misscouettes  Hey ! C'était pour savoir si vous étiez satisfaits de ce qu'on avait déjà fait sur cette commande :)

**Comment by incognitomada** [comment]
Salut j'ai fait une description de git checkout et j'ai remplie git checkout -- <path> Vous avez bien reçu ?

**Comment by Iwantaponey** [comment]
oui
@in202-uvsq/2015-release-manager J AI FINI
