### ISSUE TITLE
git status et git show

### ISSUE THREAD

**Issue by defeo** [in202-uvsq/git-manual#5]
Décrire les commandes `git status` et `git show`. Décrire en particulier les deux formes de show:

- `git show <commit>` et
- `git show <branche>:<fichier>`.

Décrire les options

- `git show --pretty`,
- `git show --stat`,
- `git status -u`,
- `git status -b`.

Assigné à : @moumzy, @pierre-cauletUVSQ, @SuzanneAir

**Comment by pierre-cauletUVSQ** [comment]
Je vous propose, puisque l'on est 3 de faire chacun 2 commandes.
Répondez en indiquant ce que vous préferez faire (+tester)

**Comment by SuzanneAir** [comment]
je veux bien faire git show --pretty et git show --stat ça a l'air sympa ^^

**Comment by pierre-cauletUVSQ** [comment]
ok je me lance donc sur git statusu et b .

**Comment by moumzy** [comment]
Daccord. Je m'occupe donc de git show commit et git show <branche>:<fichier>.

**Comment by moumzy** [comment]
Daccord. Je m'occupe donc de git show commit et git show <branche>:<fichier>.

**Comment by moumzy** [comment]
Daccord :) ! Je moccupe de git show commit et git show <branche> : <fichier>.

**Comment by moumzy** [comment]
D'accord :). Je m'occupe des deux premiers.
Je rappelle qu'on a designer SuzanneAir comme "mini" chef.

**Comment by SuzanneAir** [comment]
on s'occupe d'abord chacun de ses commandes ! bon courage les gars ^^

**Comment by pierre-cauletUVSQ** [comment]
Il faudra aussi décrire git show et git status sans option il me semble (rapide mais a ne pas oublier...)

**Comment by moumzy** [comment]
Je veux bien m'occuper de décrire brièvement git show.

**Comment by SuzanneAir** [comment]
ok thibault ! tu veux faire git status pierre ?

**Comment by pierre-cauletUVSQ** [comment]
OK. je commence par les deux autres par contre

**Comment by SuzanneAir** [comment]
j'ai terminé git show --pretty

**Comment by SuzanneAir** [comment]
attention aux modifications du squelette

**Comment by SuzanneAir** [comment]
euh apparemment faut qu'on se suive. donc comment on gère ça ?

**Comment by moumzy** [comment]
Faut qu'on definisse un task leader et on a deux choix pour proceder :
1) Le task leader nous donne les droit d'écriture sur son Fork.
2) On travaille chacun sur son Fork et on envoie une pull request au Leader.

**Comment by moumzy** [comment]
Vu comment on es partie la 2eme option est surement plus pratique.

**Comment by celinec** [comment]
Bonjour, je voudrais savoir si vous rencontrez un quelconque problème dans la création de vos pages HTML car nous n'avons eu aucun pull request de votre part. 
Je vous rappelle qu'il nous faudrait au moins un pull request d'ici ce soir (même si vos fichiers sont toujours incomplets) afin de voir si vous avez des problèmes pour faire ces pull request, pour qu'on puisse vous aider sans devoir s'y prendre à la dernière minute.

**Comment by moumzy** [comment]
Bonjour on a pas encore decider de qui s'occupait des pull request. Moi je veux bien faire, j'ai deja presque fini ma page mais concretement vous attendez quoi ? Si j'ai une réponse rapides en sortant de l'anglais j'ai 30min pr le faire.
ps : C'est normal que les noms des commandes rapetissent au fur et a mesure ? j'ai pas l'impression donc soit je code mal, soit c'est vous ! 
ps2 : Pour pas attendre le dernier moment je propose de se retrouver devant la BU a 18H30 !
mon numéro : 0667378251

**Comment by celinec** [comment]
On souhaite simplement un pull request de votre part avant ce soir pour qu'on puisse faire l'index. Même si vos fichiers ne sont pas finis il nous les faut, vous pourrez toujours les modifier plus tard ce n'est pas un problème.
Il faut seulement nous envoyer vos fichiers de commandes sans nous envoyer le fichier squelette

**Comment by moumzy** [comment]
Le soucis c'est qu'on est pas sure de comment le faire (pour faire bien). C'est pour sa que je proposais qu'on prenne 10 minutes pour voir sa. Et on est pas un cas isoler donc après moi je pourrais aussi expliquer aux autres.
De plus j'ai une ou 2 questions complémentaire et j'aimerais des réponses pour avancer sans gêner les autres.

**Comment by celinec** [comment]
Pour savoir comment faire un pull request tu as la page wiki "Forker correctement et créer une pull request" qui te l'expliques (en bas de la page). Tu peux tenter de faire des pull request autant que tu veux jusqu'à ce que ça marche bien.
Pour tes autres questions tu peux nous les poser dans l'issue Foire aux questions parce qu'effectivement ce n'est pas un cas isolé et ça permettra à tout le monde de trouver la réponse

**Comment by SuzanneAir** [comment]
https://github.com/SuzanneAir/git-manual

**Comment by pierre-cauletUVSQ** [comment]
En fait on a confondu hier soir, Thibault et Suzanne vous devez faire une page ensemble sur git show, alors que je dois en creer une seule et l'envoyer a Suzanne pour git status.

**Comment by pierre-cauletUVSQ** [comment]
J'ai trop gérer ce matin, j'ai réussi a finir la commande git status (avec les options -u et -b), créer le pull request avec ton git manual @SuzanneAir , et merge directement (nom du commit Fin git status) puisqu'il n'y avait pas de conflits (seulement l'ajout de la page) et que tu m'avais donné les droits hier soir.
Si vous avez des questions/remarque n'hésitez pas.
Il faut maintenant que vous créiez (?) une seule page avec toutes les commandes git show (tu en a fait plusieures @SuzanneAir , et il manque celles de @moumzy ).
Voila, a bientot ;)

**Comment by pierre-cauletUVSQ** [comment]
Le nouveau pull request correspond aux ajouts demandés par Corentin pour le CSS (voir le wiki) : 
j'ai encadré les balises <code> par des balises <div class=code> (pour les exemples)
Faites de même pour ne pas avoir de problemes ensuite.
Pensez egalement a transformer les h1 en h3 et h2 en h4 (oui, ils s'y sont mal pris).

**Comment by pierre-cauletUVSQ** [comment]
haha les balises ne passent pas (je remplace les supérieurs/inférieurs par des crochets)
j'ai encadré les balise [code] par des balises [div class=code]
Voila, bon courage

**Comment by defeo** [comment]
`<` s'écrit `&lt;` en html. `>` s'écrit `&gt;`.

**Comment by Misscouettes** [comment]
Yop, c'est fini ici ?

**Comment by moumzy** [comment]
Oui. SuzanneAir (TaskLeader) a dit que tout était ok.

**Comment by Misscouettes** [comment]
Ok, donc je vais fermer ce canal
