### ISSUE TITLE
git log

### ISSUE THREAD

**Issue by defeo** [in202-uvsq/git-manual#6]
Décrire la commande `git log`. Décrire en particulier les options

- `git log --stat`,
- `git log --full-diff`.

Décrire les formes

- `git log <commit>..<commit>` et
- `git log <commit>...<commit>.

Assigné à : @Mr-Nico-972, @Ousam, @Protosspaspris

**Comment by Ousam** [comment]
@Protosspaspris tu veux travailler en donnant les droits à tout le monde comme a dit le prof ?

**Comment by Misscouettes** [comment]
Bonjour, je voulais juste savoir si vous aviez un problème ou non, car vous n'avez fait aucun pull request. On en a besoin, même si vous nous envoyez un squelette non remplit, pour faire l'index.html (nom du fichier et voir si vous êtes sur la bonne voie).

**Comment by Ousam** [comment]
Bonjour, On a eu un problème qui a été réglé. Je t'envoi un pull request d'une commande d'ici quelques minutes. Désolé pour ce petit souci !

**Comment by Ousam** [comment]
Je viens de faire un pull request pour la commande git log. Tenez moi au courant pour le reste merci !

**Comment by Protosspaspris** [comment]
j'ai fini pour le log full diff,vous êtes ok pour que j'envoie la pull request ?

**Comment by Ousam** [comment]
Enfaite il faut que tout soit sur une page pour le gît log donc essaye de me faire une pullrequest pour que je puisse ensuite en faire aux release manager

**Comment by Protosspaspris** [comment]
ok

**Comment by Protosspaspris** [comment]
au pire,fork mon machin

**Comment by Misscouettes** [comment]
Ousam a deja fait un pull request, donc essaye de pousser tes commit vers le fichier de ousam et après il fera un pull request quand tout aura fini.

**Comment by Misscouettes** [comment]
Sera*

**Comment by Protosspaspris** [comment]
je viens de commit un html avec nos deux parties après avoir reforké son dossier,donc pas besoin de pousser mes commit

**Comment by Ousam** [comment]
vous en êtes ou pour le reste la ?

**Comment by Protosspaspris** [comment]
ben comme dit plus haut,j'ai fait mon truc

**Comment by Misscouettes** [comment]
Yop, c'est fini ici ?

**Comment by Ousam** [comment]
Yees normalement !

**Comment by Misscouettes** [comment]
Ok, donc je ferme ici

**Comment by Misscouettes** [comment]
Il y a un problème ici au niveau de l'appel du CSS c'est <link href="../css/style.css" rel="stylesheet" type="text/css"> au lieu de <link href="css/commandes.css" rel="stylesheet" type"text/css">. Tu peux changer vite fait ?

**Comment by Misscouettes** [comment]
Tu y es presque ^^ (désolé j'avais oublié que les crochets ne s'affichaient pas) c'est "link href="../css/style.css" rel="stylesheet" type="text/css"" pour le css (remplace les premiers et derniers guillemets pas des crochets)

**Comment by Nambrok** [comment]
Je me suis occupé du css de git_log.html.
