### ISSUE TITLE
git branch

### ISSUE THREAD

**Issue by defeo** [in202-uvsq/git-manual#8]
Décrire la commande `git branch`. Décrire en particulier les options

- `git branch --track`
- `git branch --set-upstream`
- `git branch --set-upstream-to`, `git branch -u`
- `git branch -m`, `git branch -M`,
- `git branch -d`, `git branch -D`.

Assigné à: @Melanie13340 , @stefou , @MaxouUVSQ

**Comment by MaxouUVSQ** [comment]
ki fer koi

**Comment by Melanie13340** [comment]
Bon.. Comment qu'on fait?

**Comment by MaxouUVSQ** [comment]
Je propose qu'il y en ait un qui s'occupe de présenter git branch et du point 1, un autre qui fasse les point 2 et 3 et un autre qui fasse lles points 4 et 5

**Comment by Melanie13340** [comment]
On fait la plouf?

**Comment by MaxouUVSQ** [comment]
tu fait la pouf ?

**Comment by stefou** [comment]
on tire sa a la courte paille ?

**Comment by Melanie13340** [comment]
Fais*  ça*
Bah ouais! Am-str'am-gram pik-et-pik et col-é-gram bourre-et-bourre et ra-ta-tam AM-STRAM-GRAM

**Comment by Melanie13340** [comment]
POINT 3-4 :)

**Comment by MaxouUVSQ** [comment]
Je m'occupe de présenter git branch ("introduction") et git branch --track

**Comment by Melanie13340** [comment]
git branch --set-upstream
git branch --set-upstream-to, git branch -u

**Comment by MaxouUVSQ** [comment]
prévenez moi si vous arrivez à cloner

**Comment by celinec** [comment]
Bonjour, je voudrais savoir si vous rencontrez un quelconque problème dans la création de vos pages HTML car nous n'avons eu aucun pull request de votre part et n'avons aucune nouvelle. 
Je vous rappelle qu'il nous faudrait au moins un pull request d'ici ce soir (même si vos fichiers sont toujours incomplets) afin de voir si vous avez des problèmes pour faire ces pull request, pour qu'on puisse vous aider sans devoir s'y prendre à la dernière minute.
La foire aux questions nous permettra de vous répondre

**Comment by Melanie13340** [comment]
Oui clairement je rencontre un probleme, je ne sais pas comment faire..

**Comment by Melanie13340** [comment]
Bon, j'expose le probleme, deja c'est ne anglais et j'avoue que j'ai du mal a faire les traduction, ensuite pour partager les fichiers avec mes binomes j'ai creer un repertoire, j'ai forker le repertoire ou il faut faire les pull request.. Mais après (et desole pour ceux qui trouveront ca debile) je ne sais pas comment faire, si je pouvais avoir une explication un peu moins technique ce serais cool! Merci :)

**Comment by celinec** [comment]
Alors pour l'anglais je ne suis pas une référence, mais si c'est du vocabulaire tu peux toujours utiliser un dico ou un traducteur, on cherche pas de la traduction littéraire donc ca passe
Ensuite j'essaye de regarder ou est le répertoire que tu as créé en forkant le répertoire principal mais je ne le vois pas, tu l'as forké/crée quand?
Si tu as fait ton répertoire tu peux soit :
- ajouter tes deux binomes en tant que collaborateurs, comme ca pas besoin pour eux de te faire des pull resquest il faudra juste faire attention à ne pas créer de conflits en travaillant chacun votre tour (si vous ne voulez pas devoir en résoudre)
- soit laisser ton répertoire comme ca et dire aux deux autres qu'ils doivent forker ton répertoire et te faire des pull request pour t'envoyer leur fichier

Dans les deux cas tu devras nous faire un pull request

**Comment by Melanie13340** [comment]
c'est justement le pull request qui me pose probleme, je ne sais pas comment on faite pour vous "pull requester" ^^

**Comment by celinec** [comment]
x)
Alors la tu fais comme dans le wiki : tu vas dans le répertoire que tu as créés, puis tu trouves un bouton vert, tu donnes un nom à ton pull request et des explications pour nous dire ce qu'on doit en faire et nous on te dit si c'est ok ou ce qu'il faut changer
Par contre ton répertoire c'est lequel? Que je te dise déja s'il va y avoir des problèmes

**Comment by Melanie13340** [comment]
Il s'appel TD5, je sais que j'abuse mais ce soir je suis vraiment dans l'impossibilité de le faire, je vous envois tout demain! Promis!

**Comment by Melanie13340** [comment]
J'attend vos fichier dans repertoire TD5, le miens sera fini ce soir! Jeudi 18-19h j'envois tout, fini ou non

**Comment by Melanie13340** [comment]
@defeo est-ce que les couleurs pour les commandes sont importante? Car dans mon "branch --set-upstream" le master s'affiche en vert. Dois-je voir ca avec la personne qui s'occupe du CSS?

**Comment by defeo** [comment]
Git utilise les couleurs seulement dans les shells qui le supportent. Cette information est redondante avec les autres affichages. Dans le cas de `git branch`, la branche colorée en vert est la même qui est précédée par un astérisque.

Au vu de ça :  http://in202-uvsq.github.io/git-manual/branch.html, avant de me préoccuper des couleurs je me préoccuperais d'écrire des phrases qui font grammaticalement du sens en français.

**Comment by Melanie13340** [comment]
Je sais bien mais ce n'est pas fini, c'était juste pour faire un pull request comme cela était prévu, au vu d'avoir nos nom de pages.. L'explication était une traduction littérale pour comprendre mon sujet. Il est clair que je ne laisserais pas cela ainsi

**Comment by MaxouUVSQ** [comment]
http://pastebin.com/ZjdFg4Xs
Yo, j'arrive pas à push mes changements donc faute de mieux j'ai fait un pastebin

**Comment by stefou** [comment]
j arrives pas a push, c'est mon html

<!DOCTYPE HTML>
<head>
	<title>Nom de la commande</title>
	<meta charset="UTF-8">
	<link href="css/commandes.css" rel="stylesheet" type"text/css">
</head>

<body>
	<nav>
		<p>Menu</p>
	</nav>
	<h1 id="titreCommande">git branch -m</h1>
	<p>Permet de changer ou renomer une branche et son reflog correspondant</p>
	<h2>git branch -M</h2>
	<p>Permet de changer ou renomer une branche même si une branche avec le même nom existe deja. </p>
	<h3> git branch -d</h3>
	<p>Permet d'effacer une branche </p>
	<h4> git branch -D</h4>
	<p>Permet d'effacer une branche ne correspondant pas au status </p>
	<footer>		
		<p>Git Manual - Par Nom Utilisateur</p>
	</footer>
	
</body>

**Comment by Melanie13340** [comment]
Dans powershell clone le repertoire TP5, tu ecris ce que tu as fais la sur le fichier branch, tu le renvois sur TD5 et ca devrait aller.

**Comment by Melanie13340** [comment]
Bon, vous en etes ou? @MaxouUVSQ ?

**Comment by Melanie13340** [comment]
A 19h30 j'envois tout! Que vous ayez fais vos trucs ou pas..

**Comment by MaxouUVSQ** [comment]
J'arrive pas à éditer ton fork, c'est pour ça que je t'ai mis un pastebin ...

**Comment by Misscouettes** [comment]
Yop, alors, vous avez fini ou vous avez encore quelques soucis ?

**Comment by Melanie13340** [comment]
Jai toujours pas la partie de @MaxouUVSQ

**Comment by Melanie13340** [comment]
Mais c'est trop tard j'ai tout envoye..

**Comment by Melanie13340** [comment]
Je demande tout depuis 3 jours, c'est pas 15 minutes avant la fin qu'on m'envoit un message..

**Comment by MaxouUVSQ** [comment]
"MaxouUVSQ commented 9 hours ago"

**Comment by Melanie13340** [comment]
Autant pour moi, mais tu aurais pu me dire qqch ce matin et remettre des commentaires tout le long

**Comment by Melanie13340** [comment]
& en plus ce n'est pas le bon squelette! Bref c'est de ma faute, je vais faire en sorte de l'envoyer now.

**Comment by Melanie13340** [comment]
@in202-uvsq/2014-2015 desole pour le mini retard, j'espere que ca passe..

**Comment by Nambrok** [comment]
Il est passé, merci.
